apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: worker-cnf
  labels:
    machineconfiguration.openshift.io/role: worker-cnf
spec:
  machineConfigSelector:
    matchExpressions:
      - {
          key: machineconfiguration.openshift.io/role,
          operator: In,
          values: [worker-cnf,worker]
        }
  paused: false
  nodeSelector:
       kubernetes.io/hostname: cmp3.dsp.lab
  matchLabels:
      node-role.kubernetes.io/worker-cnf: ""
