apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: cmp1-sriov-network
  namespace: openshift-sriov-network-operator
spec:
  resourceName: mellanox_r640_cx5_25g
  networkNamespace: openshift-sriov-network-operator
  ipam: '{"type":"static","addresses": [{"address":"192.168.150.51/24", "gateway":"192.168.150.1"}],"routes": [{"dst":"192.168.50.0/24","gw":"192.168.150.1"}]}'
  capabilities: '{"mac": true, "ips": true}'
