apiVersion: v1
kind: Pod
metadata:
  name: ping
  namespace: dpdk
  annotations:
    k8s.v1.cni.cncf.io/networks: mellanox-dpdk-network-1
spec:
  nodeSelector:
    kubernetes.io/hostname: cmp3.dsp.lab
  containers:
  - name: testpmd
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: centos/tools
    resources:
      limits:
        memory: "200Mi"
        cpu: "4"
      requests:
        memory: "200Mi"
        cpu: "4"

