apiVersion: v1
kind: Pod
metadata:
  name: testpmd
  namespace: dpdk
  annotations:
    k8s.v1.cni.cncf.io/networks: mellanox-dpdk-network
spec:
  nodeSelector:
    kubernetes.io/hostname: cmp3.dsp.lab
  containers:
  - name: testpmd
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: docker.io/bmcfall/dpdk-app-centos:latest
    resources:
      limits:
              #        openshift.io/intelnics: "1"
        memory: "4Gi"
        cpu: "4"
        hugepages-1Gi: "4Gi"
      requests:
              #      openshift.io/intelnics: "1"
        memory: "4Gi"
        cpu: "4"
        hugepages-1Gi: "4Gi"
    volumes:
    - name: hugepage
      emptyDir:


