apiVersion: v1
kind: Pod
metadata:
  name: compute-1-pod
  namespace: openshift-sriov-network-operator
  annotations:
    k8s.v1.cni.cncf.io/networks: compute-1-vf0-sriov-network
spec:
  nodeSelector:
    kubernetes.io/hostname: r191c1.dsp.lab
  containers:
  - name: example-pod
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: centos/tools
